### ISSUE TITLE
emojify on npm

### ISSUE THREAD

**Issue by danthareja** [Andersos/feedback#1]
Hey @Andersos!

I'm working on a new emoji based tool and am about to ship. I was perusing npm and saw your package: https://www.npmjs.com/package/emojify

The link to the source repository was broken, and it seems to be a bit out of date. Are you still maintaining this package? If not, would you freeing up the name? I'd love to use `emojify` as my package name.

**Comment by danthareja** [comment]
Any movement on this @Andersos?

**Comment by Andersos** [comment]
Hey, sure you can have the name =)

I have added you as a collaborator.

**Comment by danthareja** [comment]
Cheers! I just hit you back with a response to your email. Think you can `npm unpublish emojify` instead?
